---
    - name: Setting up Security/Firewall Group
      ec2_group:
         name: Vikash_AWS_Security_Grp
         description: Rules for Allowing Traffic on port 80 and 443
         region: us-west-2
         rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
         rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         group: Vikash_AWS_Security_Grp 
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         instance_tags:
           Name: WEB01
           Owner: Vikash
         vpc_subnet_id: subnet-47e7071c 
         assign_public_ip: yes
         region: "{{ region }}"
      register: ec2
    - name: Allocating elastic IP to instance
      ec2_eip:
         in_vpc: yes
         reuse_existing_ip_allowed: yes
         state: present
         region:  "{{ region }}"
         instance_id: "{{ ec2.instance_ids[0] }}"
      register: instance_eip
    - name: Add the machine to the inventory
      add_host:
         hostname: "{{ ec2.instance_ids[0] }}"
         groupname: web
    - name: Print all ec2 variables
      debug: var=ec2
